function data = biologic_read(filename, dataLines)
%IMPORTFILE Import data from a text file
%  MAAZZAMSL087NACHUMIN3V01 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the numeric data.
%
%  MAAZZAMSL087NACHUMIN3V01 = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  MAAzzamSL087nachumin3V01 = importfile("C:\Publikation\Frequency dispersion and DRT\MJ1_SL87_EIS_SOC_10_90\MA_Azzam_SL087_nach_umin_3V01.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-Sep-2022 16:09:43

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["freqHz", "ReZOhm", "ImZOhm"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["freqHz", "ReZOhm", "ImZOhm"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["freqHz", "ReZOhm", "ImZOhm"], "DecimalSeparator", ",");
opts = setvaropts(opts, ["freqHz", "ReZOhm", "ImZOhm"], "ThousandsSeparator", ".");

% Import the data
MAAzzamSL087nachumin3V01 = readtable(filename, opts);

%% Convert to output type
data = table2array(MAAzzamSL087nachumin3V01);
end