function [fitresult, gof] = createFit(x, y,type)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-Jan-2021 22:27:52


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype(type);
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [0.0100893415155769 -3.80560927400216 0.172867648081701 0.00949450931589993 -3.39503250817935 0.171822835476429 0.00815508307317032 -1.53241596078808 0.113780446245481 0.00717498011681255 -2.86428693284743 0.201859255588785 0.00676592345509561 -0.0303058419241502 0.132493007369833 0.0066150059295526 -1.74271137742903 0.141249182436578 0.00576033960151051 -1.35216274652441 0.163341651715947 0.00558552347295602 0.210031777094079 0.170608841906298];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'y vs. x', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'y', 'Interpreter', 'none' );
grid on


